#ifndef SRC_DEFINITIONS_H
#define SRC_DEFINITIONS_H

#define JOYSTICK1_PORT 1
#define JOYSTICK2_PORT 2

#define LEFT_TALON 0
#define RIGHT_TALON 1

#endif
/*
 * IF ANY OF THIS DANG CODE WORKS
 * I WON'T BELIEVE IT FOR A SECOND
 */
