#ifndef SRC_DEFINITIONS_H
#define SRC_DEFINITIONS_H

#define JOYSTICK1_PORT 1
#define JOYSTICK2_PORT 2
#define GAMECUBE_PORT 3

#define LEFT_TALON 0
#define LIFT_TALON 1
#define RIGHT_TALON 2


#define LEFT_ENCODER_A 8
#define LEFT_ENCODER_B 9
#define RIGHT_ENCODER_A 6
#define RIGHT_ENCODER_B 7

#define RELAY_PORT 5


#endif
